version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /root/stack_data/audiobookshelf/audiobooks:/audiobooks
      - /root/stack_data/audiobookshelf/podcasts:/podcasts
      - /root/stack_data/audiobookshelf/config:/config
      - /root/stack_data/audiobookshelf/metadata:/metadata

networks:
  default:
    external: true
    name: upstream
