version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=America/Denver
       ports:
            - 5055:5055
       volumes:
            - /root/stack_data/overseer/config:/app/config
       restart: unless-stopped

