version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /nfs/audiobookshelf/audiobooks:/audiobooks
      - /nfs/audiobookshelf/podcasts:/podcasts
      - /nfs/audiobookshelf/config:/config
      - /nfs/audiobookshelf/metadata:/metadata
    entrypoint: /bin/sh -c "mkdir -p $APP_DATA/audiobookshelf/audiobooks \
                $APP_DATA/audiobookshelf/podcasts \
                $APP_DATA/audiobookshelf/config \
                $APP_DATA/audiobookshelf/metadata"
