version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - $APP_DATA/audiobookshelf/audiobooks:/audiobooks
      - $APP_DATA/audiobookshelf/podcasts:/podcasts
      - $APP_DATA/audiobookshelf/config:/config
      - $APP_DATA/audiobookshelf/metadata:/metadata
    entrypoint: /bin/sh -c "mkdir -p $APP_DATA/audiobookshelf/audiobooks && \
                            mkdir -p $APP_DATA/audiobookshelf/podcasts && \
                            mkdir -p $APP_DATA/audiobookshelf/config && \
                            mkdir -p $APP_DATA/audiobookshelf/metadata"
