version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /root/stack_data/audiobookshelf/audiobooks:/audiobooks
      - /root/stack_data/audiobookshelf/podcasts:/podcasts
      - /root/stack_data/audiobookshelf/config:/config
      - /root/stack_data/audiobookshelf/metadata:/metadata
    entrypoint: /bin/sh -c "mkdir -p /root/stack_data/audiobookshelf/audiobooks && \
                            mkdir -p /root/stack_data/audiobookshelf/podcasts && \
                            mkdir -p /root/stack_data/audiobookshelf/config && \
                            mkdir -p /root/stack_data/audiobookshelf/metadata"
