version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:80
    volumes:
      - /root/stack_data/jellyfin/config:/config
      - /root/stack_data/jellyfin/cache:/cache
      - /root/media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    entrypoint: /bin/sh -c "mkdir -p /root/stack_data/jellyfin/config && \
                            mkdir -p /root/stack_data/jellyfin/cache"
     #                       mkdir -p /root/stack_data/audiobookshelf/config && \
     #                       mkdir -p /root/stack_data/audiobookshelf/metadata"
    
